version: "3.4"

services:
  transactions-gateway-app:
    container_name: twomenonebank-transactions-gateway-app
    image: happypiece/twomenonebank:transactions-gateway
    depends_on:
      - db
      - rabbit
    ports:
      - "0.0.0.0:30000:30000"
      - "0.0.0.0:30001:30001"
    environment:
      ASPNETCORE_HTTP_PORT: https://+:30001
      ASPNETCORE_URLS: http://+:30000
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    networks:
      - twomenonebank-network
