include:
  - svc_Core/docker-compose.yml
  - svc_Auth/docker-compose.yml
  - svc_Credit/docker-compose.yml
  - svc_TransactionsGateway/docker-compose.yml
  - svc_Monitoring/docker-compose.yml

services:
  db:
    container_name: twomenonebank-db
    hostname: twomenonebank-db-host
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER:-twomenonebank}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-twomenonebank}
      POSTGRES_DB: twomenonebank
    volumes:
      - twomenonebank-db:/var/lib/postgresql/data
    restart: always
    networks:
      - twomenonebank-network

  rabbit:
    container_name: twomenonebank-rabbit
    hostname: twomenonebank-rabbit-host
    image: rabbitmq:management
    ports:
      - "${RABBIT_PORT:-5672}:5672"
      - "${RABBIT_MANAGEMENT_PORT:-15672}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD:-guest}
    volumes:
      - twomenonebank-rabbit:/var/lib/rabbitmq/
    restart: always
    networks:
      - twomenonebank-network
  
  elasticsearch:
    container_name: twomenonebank-elasticsearch
    hostname: twomenonebank-elasticsearch-host
    image: elasticsearch:8.13.0
    expose:
      - 9200
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - twomenonebank-network

  kibana:
    container_name: twomenonebank-kibana
    image: kibana:8.13.0
    ports:
      - ${KIBANA_PORT:-5601}:5601
    volumes:
      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - twomenonebank-network

volumes:
  twomenonebank-db:
  twomenonebank-rabbit:

networks:
  twomenonebank-network:
