include:
  - svc_Core/docker-compose.yml
  - svc_Auth/docker-compose.yml
  - svc_Credit/docker-compose.yml
  - svc_TransactionsGateway/docker-compose.yml

services:
  db:
    container_name: twomenonebank-db
    hostname: twomenonebank-db-host
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER:-twomenonebank}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-twomenonebank}
      POSTGRES_DB: twomenonebank
    volumes:
      - twomenonebank-db:/var/lib/postgresql/data
    restart: always
    networks:
      - twomenonebank-network

  rabbit:
    container_name: twomenonebank-rabbit
    hostname: twomenonebank-rabbit-host
    image: rabbitmq:management
    ports:
      - "${RABBIT_PORT:-5672}:5672"
      - "${RABBIT_MANAGEMENT_PORT:-15672}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD:-guest}
    volumes:
      - twomenonebank-rabbit:/var/lib/rabbitmq/
    restart: always
    networks:
      - twomenonebank-network

volumes:
  twomenonebank-db:
  twomenonebank-rabbit:

networks:
  twomenonebank-network:
