version: "3.4"

services:
  app:
    container_name: twomenonebank-core-app
    image: happypiece/twomenonebank:core
    depends_on:
      - db
    ports:
      - "0.0.0.0:27000:27000"
      - "0.0.0.0:27001:27001"
    environment:
      ASPNETCORE_HTTP_PORT: https://+:27001
      ASPNETCORE_URLS: http://+:27000
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    networks:
      - twomenonebank-network

volumes:
  twomenonebank-db:

networks:
  twomenonebank-network:
