services:
  employee-bff:
    image: happypiece/twomenonebank:employee-bff
    ports:
      - "5000:5000"
    environment:
      - BFF_PORT=5055
      - AUTH_HOST=http://185.177.219.207:28000
      - CREDIT_HOST=http://localhost:5278
      - CORE_HOST=http://localhost:5278
      - TRANSACTIONS_HOST=http://localhost:8888
