services:
  monitoring-app:
    container_name: twomenonebank-monitoring-app
    hostname: twomenonebank-monitoring-host
    image: happypiece/twomenonebank:monitoring
    depends_on:
      - elasticsearch
    expose:
      - 32000
    environment:
      ASPNETCORE_HTTP_PORT: https://+:32001
      ASPNETCORE_URLS: http://+:32000
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    networks:
      - twomenonebank-network

volumes:
  twomenonebank-db:

networks:
  twomenonebank-network:
